<?php
/**
 * @author ShiO
 */
class URLCallException extends BaseException{
    public function __construct($message, $code, Exception $previous) {
        parent::__construct($message, $code, $previous);
    }

    public function __toString() {
        parent::__toString(); // TODO: Change the autogenerated stub
    }

}